swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swaggeroni

consumes:
  - application/json
produces:
  - application/json
  - application/xml

basePath: /v1

paths:
  /airports:
    get:
      operationId: app.get_airports
      tags:
        - airports
      summary: Get list of all airports.
      description: Returns a list of all the airports.
      produces:
        - text/csv
        - application/json

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Airports'

  /airports/{airport_code}/carriers:
    get:
      operationId: app.get_airport_carriers
      tags:
        - airports
      summary: Get all carriers on a specific airport.
      description: Returns a list of all carriers operating on a given airport.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: path
          name: airport_code
          type: string
          required: true
          description: code of the airport

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Carriers'

  /carriers:
    get:
      operationId: app.get_carriers
      tags:
        - carriers
      summary: Get a list of all carriers.
      description: Returns list of all carriers operating in the USA.
      produces:
        - text/csv
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Carriers'

  /statistics:
    get:
      operationId: app.get_statistics
      tags:
        - statistics
      summary: Get all statistics for a given carrier.
      description: Returns a list of carrier statistics depending on parameters.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: query
          name: carrier
          type: string
          required: true
          description: code of the carrier
        - in: query
          name: month
          type: integer
          required: false
          description: month
        - in: query
          name: airport
          type: string
          required: true
          description: code of the airport

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Statistics'

    post:
      operationId: app.post_statistics
      tags:
        - statistics
      summary: Post a new carrier statistic into the database.
      description: Adds a new carrier statistic entry into the database.
      consumes:
        - application/json
      parameters:
        - in: body
          name: request_body
          description: data entry to be updated.
          required: true
          schema:
            $ref: '#/definitions/Statistics'

      responses:
        200:
          description: OK

    put:
      operationId: app.put_statistics
      tags:
        - statistics
      summary: Updates the statistics for a given carrier, airport and time in the request body.
      description: Update statistics for carrier.
      consumes:
        - application/json
      parameters:
        - in: body
          name: request_body
          description: data entry to be updated.
          required: true
          schema:
            $ref: '#/definitions/Statistics'
      responses:
        200:
          description: OK

    delete:
      operationId: app.delete_statistics
      tags:
        - statistics
      summary: Deletes the entry corresponding to the carrier, airport and time.
      description: Delete entry.
      consumes:
        - application/json
      parameters:
        - in: body
          name: request_body
          description: data entry to be updated.
          required: true
          schema:
            $ref: '#/definitions/Statistics'
      responses:
        200:
          description: OK

  /statistics/flights:
    get:
      operationId: app.get_flights
      tags:
        - statistics
      summary: Get flight statistic for a given carrier.
      description: Retrieve performance stats for a carrier.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: query
          name: carrier_code
          type: string
          required: true
          description: code of the carrier
        - in: query
          name: airport
          type: string
          required: true
          description: code of the airport
        - in: query
          name: month
          type: integer
          required: false
          description: month

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Flights'

  /statistics/delays:
    get:
      operationId: app.get_delays
      tags:
        - statistics
      summary: Get delays in minutes per carrier.
      description: Returns a list of carrier specific delays per minute.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: query
          name: carrier_specific
          type: string
          required: false
          description: carrier specific reasons/all reasons
        - in: query
          name: airport
          type: string
          required: false
          description: code of the airport
        - in: query
          name: month
          type: integer
          required: false
          description: month
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Delays'

  /statistics/descriptive:
    get:
      operationId: app.get_delay_statistics
      tags:
        - statistics
      summary: Get descriptive statistics for two airports.
      description: Returns descriptive statistics; mean, median and standard deviation. For two airports with a carrier specific reason, for all or a certain carrier.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: query
          name: carrier
          type: string
          required: false
          description: code of the carrier.
        - in: query
          name: carrier_specific
          type: string
          required: false
          description: carrier specific reasons/all reasons
        - in: query
          name: airport1
          type: string
          required: true
          description: One of the two airports
        - in: query
          name: airport2
          type: string
          required: true
          description: One of the two airports

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Descriptive_statistics'


definitions:
  Link:
    type: object
    properties:
      rel:
        type: string
      href:
        type: string
        format: uri

  Airport:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      links:
        type: array
        items:
          $ref: '#/definitions/Link'

  Airports:
    type: array
    items:
      $ref: '#/definitions/Airport'

  Carrier:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      links:
        type: array
        items:
          $ref: '#/definitions/Link'

  Carriers:
    type: array
    items:
      $ref: '#/definitions/Carrier'

  Delays:
    type: object
    properties:
      late_aircraft:
        type: integer
      weather:
        type: integer
      security:
        type: integer
      national_aviation_system:
        type: integer
      carrier:
        type: integer

  Flights:
    type: object
    properties:
      cancelled:
        type: integer
      on_time:
        type: integer
      total:
        type: integer
      delayed:
        type: integer
      diverted:
        type: integer

  Minutes_delayed:
    type: object
    properties:
      late_aircraft:
        type: integer
      weather:
        type: integer
      carrier:
        type: integer
      security:
        type: integer
      total:
        type: integer
      national_aviation_system:
        type: integer

  Statistics:
    type: object
    properties:
      flights:
        $ref: '#/definitions/Flights'
      delays:
        $ref: '#/definitions/Delays'
      minutes_delayed:
        $ref: '#/definitions/Minutes_delayed'

  Time:
    type: object
    properties:
      label:
        type: string
      year:
        type: integer
      month:
        type: integer

  Descriptive_statistics:
    type: object
    properties:
      mean:
        type: integer
      median:
        type: integer
      std_dev:
        type: integer







