swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swaggeroni

consumes:
  - application/json
produces:
  - application/json
  - application/xml

basePath: /v1

paths:
  /airports:
    get:
      operationId: app.get_airports
      tags:
        - airports
      summary: blabla
      description: Read the list of airports
      produces:
        - text/csv
        - application/json
      parameters:
        - name: content_type
          in: query
          description: json/xml
          required: false
          type: string

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Airports'

  /airports/{airport_code}/carriers:
    get:
      operationId: app.get_airport_carriers
      tags:
        - airports
      summary: blabla
      description: Read list of carriers for a given airport
      produces:
        - text/csv
        - application/json
      parameters:
        - in: path
          name: airport_code
          type: string
          required: true
          description: code of the airport

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Carriers'

  /carriers:
    get:
      operationId: app.get_carriers
      tags:
        - carriers
      summary: blabla
      description: Returns list of all carriers operating in the USA.
      produces:
        - text/csv
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Carriers'

  /carriers/{carrier_code}/statistics:
    get:
      operationId: app.get_statistics
      tags:
        - carriers
      summary: blabla
      description: statistics something something
      produces:
        - text/csv
        - application/json
      parameters:
        - in: path
          name: carrier_code
          type: string
          required: true
          description: code of the carrier
        - in: query
          name: month
          type: integer
          required: false
          description: month
        - in: query
          name: airport
          type: string
          required: true
          description: code of the airport

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Statistics'

#    post:
#      operationId: app.post_statistics
#      tags:
#        - carriers
#      summary: blabla
#      description: Read lis of carriers for a given airport
#      produces:
#        - text/csv
#        - application/json
#      parameters:
#        - in: path
#          name: carrier_code
#          type: string
#          required: true
#          description: code of the carrier
#
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Carriers'
#
#    put:
#      operationId: app.put_statistics
#      tags:
#        - carriers
#      summary: blabla
#      description: Update statistics for carrier
#      produces:
#        - text/csv
#        - application/json
#      parameters:
#        - in: path
#          name: carrier_code
#          type: string
#          required: true
#          description: code of the carrier
#
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Carriers'
#
#    delete:
#      operationId: app.delete_statistics
#      tags:
#        - carriers
#      summary: blabla
#      description: Delete statistics for carrier.
#      produces:
#        - text/csv
#        - application/json
#      parameters:
#        - in: path
#          name: carrier_code
#          type: string
#          required: true
#          description: code of the carrier
#
#      responses:
#        200:
#          description: OK
#          schema:
#            $ref: '#/definitions/Carriers'

  /carriers/{carrier_code}/flights:
    get:
      operationId: app.get_flights
      tags:
        - carriers
      summary: blabla
      description: Retrieve performance stats for a carrier.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: path
          name: carrier_code
          type: string
          required: true
          description: code of the carrier
        - in: query
          name: airport
          type: string
          required: true
          description: code of the airport
        - in: query
          name: month
          type: integer
          required: false
          description: month

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Flights'

  /carriers/delays:
    get:
      operationId: app.get_delays
      tags:
        - carriers
      summary: blabla
      description: Get delays in minutes per carrier.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: query
          name: carrier_specific
          type: string
          required: false
          description: carrier specific reasons/all reasons
        - in: query
          name: airport
          type: string
          required: false
          description: code of the airport
        - in: query
          name: month
          type: integer
          required: false
          description: month
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Delays'

  /carriers/delays/statistics:
    get:
      operationId: app.get_delay_statistics
      tags:
        - carriers
      summary: blabla
      description: Returns descriptive statistics for a specific carrier or all carriers.
      produces:
        - text/csv
        - application/json
      parameters:
        - in: query
          name: carrier
          type: string
          required: false
          description: code of the carrier.
        - in: query
          name: carrier_specific
          type: string
          required: false
          description: carrier specific reasons/all reasons
        - in: query
          name: airport1
          type: string
          required: true
          description: One of the two airports
        - in: query
          name: airport2
          type: string
          required: true
          description: One of the two airports

      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Descriptive_statistics'


definitions:
  Link:
    type: object
    properties:
      rel:
        type: string
      href:
        type: string
        format: uri

  Airport:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      links:
        type: array
        items:
          $ref: '#/definitions/Link'

  Airports:
    type: array
    items:
      $ref: '#/definitions/Airport'

  Carrier:
    type: object
    properties:
      code:
        type: string
      name:
        type: string
      links:
        type: array
        items:
          $ref: '#/definitions/Link'

  Carriers:
    type: array
    items:
      $ref: '#/definitions/Carrier'

  Delays:
    type: object
    properties:
      late_aircraft:
        type: integer
      weather:
        type: integer
      security:
        type: integer
      national_aviation_system:
        type: integer
      carrier:
        type: integer

  Flights:
    type: object
    properties:
      cancelled:
        type: integer
      on_time:
        type: integer
      total:
        type: integer
      delayed:
        type: integer
      diverted:
        type: integer

  Minutes_delayed:
    type: object
    properties:
      late_aircraft:
        type: integer
      weather:
        type: integer
      carrier:
        type: integer
      security:
        type: integer
      total:
        type: integer
      national_aviation_system:
        type: integer

  Statistics:
    type: object
    properties:
      flights:
        $ref: '#/definitions/Flights'
      delays:
        $ref: '#/definitions/Delays'
      minutes_delayed:
        $ref: '#/definitions/Minutes_delayed'

  Time:
    type: object
    properties:
      label:
        type: string
      year:
        type: integer
      month:
        type: integer

  Descriptive_statistics:
    type: object
    properties:
      mean:
        type: integer
      median:
        type: integer
      std_dev:
        type: integer







